language: java
desired capabilities:
 - browser: IE
   browser_version: 7.0
   os: Windows
   os_version: XP
   browserstack.debug: true
 - browser: Firefox
   browser_version: 34.0
   os: OS X
   os_version: El Capitan
   browserstack.debug: true
